---
title: "Baseline"
author: "Jack Sudds"
date: "02/08/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Package}
library(tidyverse) #install.packages("tidyverse")
library(readxl) #install.packages("readxl")
library(here) #install.packages("here")
library(janitor) #install.packages("janitor")
library(kableExtra) #install.packages("kableExtra")
library(skimr) #install.packages("skimr")
library(dplyr) #install.packages("dplyr")
library(RColorBrewer) #install.packages("RColorBrewer")
library(formattable) #install.packages("formattable")
library(wesanderson)#install.packages("wesanderson")
library(reshape2)
library(ggtext) #install.packages("ggtext")
library(psych)#install.packages("psych")
```

```{r import}

Plan_B <- read_excel(here("../data/master.xlsx"), range = "A1:AN993", sheet = "Plan_B")

Clarendon <- read_excel(here("../data/master.xlsx"), range = "A1:Y9", sheet = "data")

```

```{r cleanup}

Plan_B_clean = Plan_B[rowSums(is.na(Plan_B)) <= 31, ]

B_femur = Plan_B_clean %>% filter(Element == "femur") %>% remove_empty("cols")
B_scapula = Plan_B_clean %>% filter(Element == "scapula") %>% remove_empty("cols")
B_humerus = Plan_B_clean %>% filter(Element == "humerus")%>% remove_empty("cols")
B_radius = Plan_B_clean %>% filter(Element == "radius")%>% remove_empty("cols")
B_tibia = Plan_B_clean %>% filter(Element == "tibia")%>% remove_empty("cols")
B_astragalus = Plan_B_clean %>% filter(Element == "astragalus")%>% remove_empty("cols")
B_metacarpal = Plan_B_clean %>% filter(Element == "metacarpal")%>% remove_empty("cols")
B_metatarsal = Plan_B_clean %>% filter(Element == "metatarsal")%>% remove_empty("cols")
B_calcaneus = Plan_B_clean %>% filter(Element == "calcaneus")%>% remove_empty("cols")
B_ulna = Plan_B_clean %>% filter(Element == "ulna")%>% remove_empty("cols")

```

```{r Freq checks}

Plan_B_elements <- Plan_B_clean %>%
  count(Element)

Plan_B_sex <- Plan_B_clean %>%
  count(Sex)

Clarendon_elements <- Clarendon %>%
  count(Element)

Plan_B_long <- melt(Plan_B_clean, value.name = "measurement", id=1:9, na.rm = TRUE)
```

```{r measurement list}

Plan_C <- Plan_B_clean %>%
  filter(Site=="Phoenix Park")

Plan_C_long <- melt(Plan_C, value.name = "measurement", id=1:9, na.rm = TRUE )

C_measures_count <- Plan_C_long %>%
  count(Element, variable)

Plan_C_long <- Plan_C_long %>%
  unite(Measurement, c(Element, variable))

Plan_C_clean <- Plan_C_long %>%
  filter(!Measurement %in% c('metacarpal_Dd', 'metacarpal_DD', 'metatarsal_DD', 'metatarsal_Dd', 'radius_Dp'))

C_split <- split(Plan_C_clean, f=Plan_C_clean$Measurement)

```

```{r table building}
counts <- Plan_C_clean %>%
  count(Measurement)

min <- Plan_C_clean %>%
  group_by(Measurement) %>%
  summarise_at(vars(measurement), list(name = min))

max <- Plan_C_clean %>%
  group_by(Measurement) %>%
  summarise_at(vars(measurement), list(name = max))

mean <- Plan_C_clean %>%
  group_by(Measurement) %>%
  summarise_at(vars(measurement), list(name = mean))

sd <- Plan_C_clean %>%
  group_by(Measurement) %>%
  summarise_at(vars(measurement), list(name = sd))

CoV <- data.frame(matrix(ncol=2, nrow=39))
CoV$X1 <- min$Measurement
CoV$X2 <- round(((sd$name/mean$name)*100), digits = 2)

Baseline <- data.frame(matrix(ncol=6, nrow=39))
Baseline$X1 <- counts$Measurement
Baseline$X2 <- counts$n
Baseline$X3 <- min$name
Baseline$X4 <- max$name
Baseline$X5 <- mean$name
Baseline$X6 <-CoV$X2

colnames(Baseline)<- c('Measurement', 'n', 'Min.', 'Max.', 'Mean', 'CoV')
  

```

