---
title: "Sexual dimorphism"
author: "Jack Sudds"
date: "06/08/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Package}
library(tidyverse) #install.packages("tidyverse")
library(readxl) #install.packages("readxl")
library(here) #install.packages("here")
library(janitor) #install.packages("janitor")
library(kableExtra) #install.packages("kableExtra")
library(skimr) #install.packages("skimr")
library(dplyr) #install.packages("dplyr")
library(RColorBrewer) #install.packages("RColorBrewer")
library(formattable) #install.packages("formattable")
library(wesanderson)#install.packages("wesanderson")
library(reshape2)
library(ggtext) #install.packages("ggtext")
library(psych)#install.packages("psych")
```

```{r import}

Plan_B <- read_excel(here("../data/master.xlsx"), range = "A1:AN993", sheet = "Plan_B")

Clarendon <- read_excel(here("../data/master.xlsx"), range = "A1:Y11", sheet = "data")

```

```{r cleanup}

Plan_B_clean = Plan_B[rowSums(is.na(Plan_B)) <= 31, ]

B_femur = Plan_B_clean %>% filter(Element == "femur") %>% remove_empty("cols")
B_scapula = Plan_B_clean %>% filter(Element == "scapula") %>% remove_empty("cols")
B_humerus = Plan_B_clean %>% filter(Element == "humerus")%>% remove_empty("cols")
B_radius = Plan_B_clean %>% filter(Element == "radius")%>% remove_empty("cols")
B_tibia = Plan_B_clean %>% filter(Element == "tibia")%>% remove_empty("cols")
B_astragalus = Plan_B_clean %>% filter(Element == "astragalus")%>% remove_empty("cols")
B_metacarpal = Plan_B_clean %>% filter(Element == "metacarpal")%>% remove_empty("cols")
B_metatarsal = Plan_B_clean %>% filter(Element == "metatarsal")%>% remove_empty("cols")
B_calcaneus = Plan_B_clean %>% filter(Element == "calcaneus")%>% remove_empty("cols")
B_ulna = Plan_B_clean %>% filter(Element == "ulna")%>% remove_empty("cols")

```

```{r dimorph Femur}

ggplot(filter(B_femur, Sex!="U"), aes(x=Bd, y=SD, colour = Age, shape = Site)) +
  geom_point() +
  theme(
    plot.title = element_text(hjust = 0.5, face = 'bold'),
        panel.background = element_rect(fill = 'white'),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = 'gray'),
        axis.line = element_line(color = "black"),
        panel.grid.minor.x = element_line(color = 'gray'),
        panel.grid.minor.y = element_blank()
    ) +
  labs(
    x = "Bd",
    y = "SD",
    title = "Femur"
  )+
  facet_wrap(~Sex, scales = "free")

ggplot(filter(B_scapula, Sex!="U"), aes(x=GLP, y=SLC, colour = Age, shape = Site)) +
  geom_point() +
  theme(
    plot.title = element_text(hjust = 0.5, face = 'bold'),
        panel.background = element_rect(fill = 'white'),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = 'gray'),
        axis.line = element_line(color = "black"),
        panel.grid.minor.x = element_line(color = 'gray'),
        panel.grid.minor.y = element_blank()
    ) +
  labs(
    x = "GLP",
    y = "SLC",
    title = "Scapula"
  ) +
  facet_wrap(~Sex, scales = "free")

ggplot(filter(B_scapula, Sex!="U"), aes(x=BG, y=LG, colour = Age, shape = Site)) +
  geom_point() +
  theme(
    plot.title = element_text(hjust = 0.5, face = 'bold'),
        panel.background = element_rect(fill = 'white'),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = 'gray'),
        axis.line = element_line(color = "black"),
        panel.grid.minor.x = element_line(color = 'gray'),
        panel.grid.minor.y = element_blank()
    ) +
  labs(
    x = "GLP",
    y = "SLC",
    title = "Scapula"
  ) +
  facet_wrap(~Sex, scales = "free")

ggplot(filter(B_scapula, Sex!="U"), aes(x=GLP, y=BG, colour = Age, shape = Site)) +
  geom_point() +
  theme(
    plot.title = element_text(hjust = 0.5, face = 'bold'),
        panel.background = element_rect(fill = 'white'),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = 'gray'),
        axis.line = element_line(color = "black"),
        panel.grid.minor.x = element_line(color = 'gray'),
        panel.grid.minor.y = element_blank()
    ) +
  labs(
    x = "GLP",
    y = "SLC",
    title = "Scapula"
  ) +
  facet_wrap(~Sex, scales = "free")

ggplot(filter(B_scapula, Sex!="U"), aes(x=LG, y=SLC, colour = Age, shape = Site)) +
  geom_point() +
  theme(
    plot.title = element_text(hjust = 0.5, face = 'bold'),
        panel.background = element_rect(fill = 'white'),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = 'gray'),
        axis.line = element_line(color = "black"),
        panel.grid.minor.x = element_line(color = 'gray'),
        panel.grid.minor.y = element_blank()
    ) +
  labs(
    x = "GLP",
    y = "SLC",
    title = "Scapula"
  ) +
  facet_wrap(~Sex, scales = "free")

```

